import React from 'react';

export default function () {
  return (
    <section className="pt-52 px-8 pb-10 container mx-auto">
      <h1 className="text-white text-6xl font-bold tracking-wide mb-5 ">Privacy Policy for Mobile Apps by codcut</h1>
      <p className="text-content">
        This Privacy Policy outlines how your personal information is collected, used, and disclosed by codcut. This
        policy applies exclusively to our mobile apps. By using our apps, you signify your explicit consent to our
        collection, storage, use, and disclosure of your personal information as described in this Privacy Policy.
      </p>
      <h2 className="text-3xl font-bold text-white mt-10">Definitions and key terms</h2>
      <p className="text-content">
        To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are
        referenced, are strictly defined as:
      </p>
      <ul className="list-disc pl-5">
        <li className="text-content">Cookie: Small amount of data generated by an app and saved by your device.</li>
        <li className="text-content">
          Personal Data: Any information that allows for the identification of a natural person.
        </li>
      </ul>
      <h2 className="text-3xl font-bold text-white mt-10">What Information Do We Collect?</h2>
      <p className="text-content">
        We collect information from you when you register on our app, subscribe to our newsletter, or fill out a form.
        This may include:
      </p>
      <ul className="list-disc pl-5">
        <li className="text-content">Name / Username</li>
        <li className="text-content">Email Addresses</li>
        <li className="text-content">Password</li>
      </ul>
      <h2 className="text-3xl font-bold text-white mt-10">Use of information</h2>
      <p className="text-content">We may use the information collected from you for the following purposes:</p>
      <ul className="list-disc pl-5">
        <li className="text-content">Personalize your experience</li>
        <li className="text-content">Improve customer service</li>
      </ul>
      <h2 className="text-3xl font-bold text-white mt-10">User Rights Under GDPR</h2>
      <p className="text-content">
        As per the General Data Protection Regulation (GDPR), you have several rights regarding your personal data:
      </p>
      <ul className="list-disc pl-5">
        <li className="text-content">
          Right to Erasure: You can request that we erase all personal data we hold about you. Contact us to proceed
          with this.
        </li>
        <li className="text-content">
          Data Portability: You have the right to request a copy of your data in a machine-readable format.
        </li>
      </ul>
      <h2 className="text-3xl font-bold text-white mt-10">Data Breach Notification</h2>
      <p className="text-content">In the event of a data breach, we will notify you within 72 hours of discovery.</p>
      <h2 className="text-3xl font-bold text-white mt-10">International Data Transfers</h2>
      <p className="text-content">
        Information collected via our apps may be stored anywhere in the world. By using our apps, you consent to the
        trans-border transfer and hosting of such information.
      </p>
      <h2 className="text-3xl font-bold text-white mt-10">CCPA Compliance</h2>
      <p className="text-content">
        We comply with the California Consumer Privacy Act (CCPA). You have the right to know and access your personal
        data, and you can request that we delete your personal information at any time.
      </p>
      <h2 className="text-3xl font-bold text-white mt-10">Amendments to This Policy</h2>
      <p className="text-content">
        We may update this Privacy Policy from time to time. Any changes will become effective when we post the revised
        Privacy Policy in our apps.
      </p>
      <h2 className="text-3xl font-bold text-white mt-10">Contact Us</h2>
      <p className="text-content">Don't hesitate to contact us if you have any questions.</p>
      <ul className="list-disc pl-5">
        <li className="text-content">Via Email: contact@codcut.com</li>
      </ul>
    </section>
  );
}
